import React, { Component } from 'react';
import 'simplebar'; // or "import SimpleBar from 'simplebar';" if you want to use it manually.
import 'simplebar/dist/simplebar.css';
import './SuperTable.scss';

class SuperTable extends Component {
    render() {
        return  (
            <div>
                <div className="header">
                    <div className="data-cell">Material Number</div>
                    <div className="data-cell">Vendor</div>
                    <div className="data-cell">GSM</div>
                    <div className="data-cell">Other 1</div>
                    <div className="data-cell">Other 2</div>
                    <div className="data-cell">Other 3</div>
                    <div className="data-cell">Other 4</div>
                    <div className="data-cell">Other 5</div>
                    <div className="data-cell">Other 6</div>
                    <div className="data-cell">Other 7</div>
                    <div className="data-cell">Other 8</div>
                    <div className="data-cell">Other 9</div>
                    <div className="data-cell">Other 10</div>
                </div>
                <div>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tristique justo eu urna tempus dignissim. Suspendisse tempus neque nec sem eleifend pulvinar. Etiam elementum orci vel purus pharetra, in placerat turpis egestas. Aliquam erat volutpat. Nunc sed orci nec tortor accumsan imperdiet at nec mi. Pellentesque ultrices odio ullamcorper eleifend blandit. Morbi ornare sodales volutpat. Curabitur sit amet orci fringilla lectus semper condimentum at eu risus. Quisque sed eros varius, ornare sem id, condimentum quam. Duis in erat aliquam, posuere nunc quis, ullamcorper dui. Donec facilisis felis et nunc eleifend sodales. Aliquam erat volutpat. Etiam feugiat tempus lectus. Proin tincidunt dui at nulla blandit, ut dapibus nisi rhoncus.

Donec porttitor fermentum orci, sit amet fringilla dui vehicula a. Suspendisse hendrerit velit ut arcu aliquam laoreet. Sed facilisis nec mauris eget imperdiet. Donec dui sem, congue a ex eu, sollicitudin tincidunt metus. Vivamus lacinia pretium cursus. Aliquam erat volutpat. Sed pulvinar elit ac scelerisque scelerisque. Aliquam sed dui augue.

Sed congue magna eget pellentesque fermentum. Vivamus purus ex, efficitur eu sapien non, egestas eleifend est. Nulla vehicula nisl odio, a sagittis arcu aliquam nec. Etiam nec euismod nulla, in pretium diam. Etiam tristique sem ut sagittis ornare. Phasellus rutrum magna in ante euismod ornare. Nullam convallis volutpat neque id rutrum. Donec non malesuada odio. Sed eget scelerisque sem. Pellentesque blandit lorem ut laoreet fringilla. Vestibulum pharetra dui metus, vel interdum justo convallis eu. Aliquam non erat ac tellus bibendum pharetra.

Mauris sapien tortor, placerat pulvinar facilisis iaculis, egestas id urna. Etiam vitae diam at mi facilisis aliquam. Morbi vel auctor dolor. Cras mattis placerat sem et rutrum. Sed condimentum vel ante id efficitur. Nulla ut ipsum urna. Nullam et tristique augue. Duis et tortor vitae ligula tempus laoreet. Quisque commodo, ligula in lacinia malesuada, turpis sapien ornare tortor, at vestibulum felis est in neque. Etiam facilisis, ligula vitae scelerisque lobortis, ante lacus tincidunt risus, et condimentum diam neque quis purus. Fusce placerat sollicitudin pharetra. Quisque blandit felis vitae lacus condimentum, vel elementum mi dictum. Etiam scelerisque ornare sapien, a venenatis nisl tristique in.

Sed dapibus est metus, sit amet placerat felis finibus id. Mauris sit amet erat in elit posuere finibus eu a nulla. Proin purus nisl, imperdiet eget libero accumsan, congue dapibus augue. Donec in libero in nunc egestas semper sit amet a purus. Integer et scelerisque dui. Nullam in lacus eget odio molestie vestibulum id mollis turpis. Proin sed viverra lectus, ac viverra arcu.

Cras maximus leo in purus eleifend, at aliquam ipsum eleifend. Proin lacinia metus velit, vel ullamcorper orci mattis sed. Etiam finibus arcu eget vulputate dictum. Vivamus mattis rhoncus ex laoreet ornare. Sed fringilla, nunc eget tempus molestie, eros nunc varius leo, non varius nisi dui a risus. Vivamus at nisl purus. Nulla lectus est, consectetur a urna eu, pulvinar viverra enim. Nam lobortis libero non quam volutpat, ut finibus risus laoreet. Quisque tincidunt erat vel orci lobortis auctor. Nulla et consequat lorem.

Curabitur orci odio, volutpat ac augue at, malesuada iaculis lacus. In nulla felis, scelerisque at magna sit amet, ornare fringilla libero. Maecenas ullamcorper orci sit amet orci venenatis cursus. Fusce vestibulum nisi vitae turpis aliquam, nec tristique quam consequat. Duis vehicula molestie est eu eleifend. Mauris malesuada nisl ac nibh tempor euismod. Aliquam quis quam risus.

Duis quis est sit amet nisi tincidunt commodo ut in justo. Nullam iaculis eros et porttitor venenatis. Suspendisse diam elit, rutrum viverra turpis vel, rutrum condimentum diam. Etiam pharetra scelerisque purus eu volutpat. Nullam consectetur tortor vel mauris elementum auctor. Pellentesque congue id leo sit amet scelerisque. Aliquam eu enim ac magna elementum laoreet. Nunc bibendum massa commodo nibh cursus pulvinar. Integer blandit non massa non condimentum. Donec lacinia pretium est sit amet suscipit. In luctus, turpis ac rutrum volutpat, dui nulla dictum magna, ut laoreet sapien dolor sed ante. Pellentesque sollicitudin arcu lorem, vitae aliquet mauris interdum et. Ut sapien leo, dapibus ut feugiat in, ullamcorper quis dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

Fusce justo diam, fermentum non sagittis nec, pretium vel dolor. Quisque posuere nisi quam. Curabitur a ligula massa. Proin tristique, turpis nec volutpat venenatis, orci nisl egestas mauris, in euismod ipsum dolor a urna. Vivamus iaculis urna nec purus volutpat, eu fringilla sapien lacinia. Maecenas eget cursus nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

Fusce facilisis risus in dapibus maximus. Aenean blandit rutrum lorem. Sed justo nisi, sollicitudin eget porttitor ac, sollicitudin in urna. Integer sed magna et orci porttitor convallis. Ut nulla augue, commodo vitae massa non, viverra laoreet nibh. Ut molestie risus eu nulla blandit consequat. Donec rhoncus lacinia felis, ut efficitur magna consequat vitae. Nullam bibendum est sit amet nulla dapibus mollis. Sed pulvinar nibh vel arcu rutrum suscipit quis posuere tellus. Ut dapibus tempus luctus. Duis tempor felis vel porta rutrum. Curabitur vel sapien feugiat, accumsan magna vitae, porttitor urna. Sed lacus ante, hendrerit sit amet erat vel, eleifend efficitur arcu. Praesent magna magna, eleifend at eros a, ullamcorper rutrum nisl. In nec ultricies tortor, sed finibus ipsum.

Suspendisse ac eros non dui malesuada placerat. Ut porta et orci at ullamcorper. Maecenas quis imperdiet quam. Praesent ac ultricies mauris. Aliquam erat volutpat. Donec ac sagittis dui, sed feugiat lectus. Praesent turpis ligula, pulvinar vitae faucibus sed, lobortis eu elit. Maecenas tincidunt tristique odio, vulputate hendrerit purus.

Cras bibendum mi luctus rutrum tempor. Quisque sit amet auctor orci. Sed hendrerit urna id eleifend mattis. Nulla sed odio eget nisi imperdiet tempor a a augue. Nunc ultrices placerat orci, a scelerisque sapien. Aenean non magna quis risus tempus porta. Phasellus vitae pellentesque ex, nec elementum dui.

Etiam sodales diam venenatis imperdiet dapibus. Fusce aliquet felis a lectus imperdiet dapibus. Quisque nec sapien leo. Maecenas eget ante mollis, cursus nunc sit amet, placerat dolor. Etiam ac neque id leo viverra consequat nec non nisi. Nam ac sagittis massa, non hendrerit dolor. In tincidunt elit elit, in consectetur lacus auctor auctor. Vivamus sed tempus nisl. Vestibulum at neque pellentesque, auctor quam sit amet, venenatis augue. Nullam sodales, velit nec pretium eleifend, ante sem mollis libero, eu mollis ipsum diam eget ipsum. Etiam iaculis metus purus, ac pulvinar justo tempor at.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse et leo ac nulla laoreet tempor. Etiam ut viverra lorem. Nulla eget arcu lacus. Morbi quis magna semper, blandit lacus id, consectetur mi. Donec mattis vel leo eu viverra. Aenean pulvinar commodo lectus.

Mauris non dignissim urna. Etiam varius aliquet elit. Nam nec nisi sit amet neque varius blandit. Suspendisse sem diam, rhoncus quis nisi in, varius blandit risus. Aliquam blandit dolor metus, et mollis velit mollis malesuada. In congue lectus non faucibus varius. Duis ac scelerisque arcu, ac sollicitudin urna.

In hac habitasse platea dictumst. Aenean metus elit, tempus a tempus ac, pharetra at ligula. Curabitur non augue risus. Maecenas enim eros, venenatis et quam id, sodales dapibus nisi. Morbi rhoncus pretium tortor, id dignissim urna ultrices ac. Cras at congue magna. Donec non felis venenatis, ornare enim vitae, semper turpis. Praesent a nunc ut elit dictum venenatis. Mauris tristique condimentum urna.

Maecenas non gravida neque. In at sollicitudin orci. Sed hendrerit neque in tempus convallis. Phasellus in metus sed sapien suscipit aliquam. Cras ornare nec mi ac hendrerit. Nullam in eros tortor. Mauris aliquam, libero et condimentum placerat, massa tortor faucibus est, viverra dignissim magna arcu vel nulla. Cras porta quam vitae volutpat accumsan. Cras in ex tempor, dictum velit at, imperdiet felis.

Duis aliquet libero vitae diam egestas, sit amet malesuada lorem elementum. Quisque eget sem suscipit, suscipit leo nec, consequat neque. Proin venenatis purus quis dolor suscipit mollis. Fusce vehicula nec ante eu condimentum. Etiam porta auctor nunc, sed interdum arcu ultricies in. Morbi aliquam orci ut turpis pharetra, in egestas urna suscipit. Pellentesque pretium sed libero at pretium. Phasellus nibh odio, dignissim vitae massa ac, viverra maximus orci. Pellentesque aliquet ligula neque, ut efficitur mauris accumsan at. Nullam pretium turpis sit amet lorem suscipit cursus. Quisque in pulvinar mi, nec blandit tellus.

Nunc ut est porttitor, placerat sem sit amet, tincidunt enim. In imperdiet ullamcorper tortor, a placerat mauris mollis nec. Donec imperdiet fringilla mauris, in maximus mauris. Donec viverra consectetur mollis. Suspendisse sollicitudin venenatis diam, et vehicula orci mattis quis. Praesent mollis, est et gravida lacinia, tellus diam fringilla leo, ac varius diam nunc sed risus. Vivamus cursus, risus eget gravida luctus, risus est ullamcorper neque, consequat vehicula nisl orci ac lorem. Donec bibendum sollicitudin tortor, quis porta dolor auctor vel. Maecenas tincidunt est in libero blandit maximus. Duis a magna eu lacus semper egestas id placerat massa. Nunc semper ligula vitae nunc pulvinar ultricies. Donec venenatis leo sed elit dapibus, id sollicitudin diam lobortis. Donec vestibulum neque eget justo aliquet, sed porta augue imperdiet. Sed non nisi non ligula convallis feugiat ut quis metus.

Duis nisi sem, consequat at dictum non, pretium nec quam. Vestibulum non ipsum sed orci porttitor congue. Aliquam vel accumsan enim, ut mollis velit. Vestibulum sollicitudin egestas mi nec finibus. Nulla facilisi. Quisque semper varius vehicula. Vivamus lobortis a tortor in egestas. Donec ante turpis, mollis quis sodales a, tempor eget ipsum. Proin efficitur lacinia mattis. Nulla dictum gravida nisl, eget sagittis magna ullamcorper id. Donec eget ligula leo. Sed tincidunt nisl in tellus commodo dictum. Phasellus sollicitudin tristique nibh et condimentum. Fusce consectetur placerat nunc nec vulputate. Fusce sit amet congue tortor, bibendum vestibulum dui. Mauris finibus lacinia ante.

Duis vel enim ut nunc laoreet vehicula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec rhoncus, orci a dignissim pharetra, justo mi blandit nisi, sed dictum turpis nunc sit amet arcu. Ut lobortis urna at ligula aliquam semper. Donec vitae rhoncus libero, id viverra est. Cras eu tristique nisi. Phasellus efficitur vestibulum purus, a sodales ex. Integer ac lacus quis tortor scelerisque cursus vel non ante. Curabitur placerat tempus sapien, in convallis diam consectetur id. Nam commodo auctor facilisis. Nam consequat eleifend sagittis. Morbi mattis nulla non ultrices tincidunt. Nunc leo justo, hendrerit sit amet sagittis in, dignissim eu est. Nulla ultricies augue venenatis, accumsan tortor at, elementum diam. Morbi eleifend tellus volutpat viverra laoreet. Duis interdum sodales ex.

Proin semper, ante vitae hendrerit viverra, sem arcu faucibus magna, id auctor mauris diam vitae ipsum. Nullam eros neque, lobortis eget tincidunt vel, venenatis faucibus lorem. Ut lobortis erat at nunc fringilla, vitae euismod turpis dapibus. Aliquam erat volutpat. Morbi bibendum egestas lectus nec luctus. In luctus lorem sed consequat condimentum. Praesent venenatis, orci eget convallis scelerisque, orci nisi convallis arcu, vitae aliquam dolor ligula eget lacus. Proin non feugiat eros. Cras tincidunt iaculis iaculis. Etiam ac felis sem.

Aliquam elementum nibh nec fermentum congue. Phasellus facilisis aliquam elit, at iaculis nisl ultricies vel. Sed blandit leo sed lectus pharetra, eget rhoncus lectus semper. Vestibulum a massa rutrum, suscipit lectus vitae, placerat justo. Donec sagittis sapien ac metus tincidunt, eu congue risus consectetur. In pulvinar consectetur suscipit. Mauris elit nibh, gravida nec neque vel, luctus facilisis massa.

Donec et leo pulvinar, ultrices nunc vel, aliquam sem. Aenean quis tincidunt leo. Quisque non consequat ipsum. Phasellus ullamcorper eros pulvinar auctor ullamcorper. Pellentesque neque ipsum, aliquet at tempus a, vehicula eget nunc. Curabitur lorem nulla, condimentum vel velit id, pretium aliquam mi. Fusce finibus orci eleifend, mattis erat et, gravida ipsum. Vivamus maximus nisl lacus, vel molestie lorem consequat et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam viverra tristique interdum. Nunc mollis ut dui et aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus nec pharetra massa. Nullam vitae efficitur eros. Mauris dictum molestie enim, et elementum dolor ornare ac. Pellentesque interdum lorem sed nulla tincidunt congue.

Etiam laoreet lectus vitae magna maximus vestibulum. Quisque sodales rutrum velit, ultricies condimentum nunc ultrices id. Vestibulum ultrices nisi maximus metus congue, sed porttitor arcu vehicula. Mauris finibus varius tellus ut aliquet. Praesent suscipit, purus a eleifend consectetur, orci tellus ullamcorper dui, ac venenatis odio est eu massa. Nulla tincidunt nibh turpis, in tempor enim vestibulum vel. Sed gravida arcu dolor, eget egestas massa ullamcorper non. Donec pulvinar lacus eros, non varius nunc fermentum ut. Morbi sapien massa, condimentum id fermentum quis, faucibus id justo. Vivamus turpis ipsum, sodales vitae tellus pulvinar, sollicitudin finibus tellus. Nulla efficitur lacus eget dolor tempus molestie in sed ex. Aenean laoreet vitae eros commodo consectetur. In maximus massa justo, eget ullamcorper nunc laoreet in. Praesent sed libero eget diam gravida aliquam finibus porttitor turpis. Vestibulum vel orci maximus, finibus lectus sed, suscipit elit. Etiam nec orci augue.

Donec a mi justo. Aliquam eget odio eu odio viverra feugiat. Pellentesque iaculis facilisis nibh non pharetra. Etiam posuere ac odio ut semper. Nulla at nibh vitae metus accumsan convallis. Donec non tellus non ipsum feugiat imperdiet. Nullam vel orci semper, elementum ipsum bibendum, tempor dolor. Integer mauris metus, blandit nec nunc quis, hendrerit posuere eros. Vestibulum eget elit vitae felis auctor dapibus. In in nisi et justo porttitor vehicula. Fusce quis arcu erat. Proin vehicula nunc tortor, ac rhoncus leo commodo ultricies.

Fusce feugiat libero est, et varius ex efficitur nec. Suspendisse pulvinar, dolor a venenatis malesuada, tellus sapien congue lacus, nec lacinia tortor augue id metus. Vestibulum accumsan risus ipsum, ut sollicitudin metus scelerisque ac. Integer auctor tellus vitae imperdiet tincidunt. Integer tempor condimentum ligula id tincidunt. Nunc auctor sem lectus, eleifend interdum nunc vulputate et. Nunc cursus odio a nisi molestie pharetra. Vestibulum varius, lacus et laoreet cursus, felis lorem pretium turpis, vel efficitur nisl lectus ac metus. Nulla mollis efficitur pharetra. Aliquam imperdiet suscipit leo, a dapibus risus pharetra id. In vehicula venenatis purus vitae tristique. Aliquam erat volutpat. Nam nec porttitor ante. Ut at tristique eros, sit amet tempus orci. Nulla condimentum nunc in lacinia ultrices. Aenean vitae rutrum risus, a consectetur erat.

Curabitur nibh quam, viverra quis ex non, porttitor feugiat justo. Mauris faucibus neque eu dapibus laoreet. Ut condimentum ornare metus. Maecenas tempus et velit eget consectetur. Nulla et ligula non nibh interdum ultrices id ut ipsum. Integer eleifend, erat at eleifend accumsan, turpis odio pulvinar justo, in tempor mi justo eu metus. Maecenas interdum purus purus, et posuere nulla aliquet et. Suspendisse condimentum nisl libero, sed blandit nunc pretium id. Donec nec nisi vel felis semper malesuada nec scelerisque massa. Vivamus pretium, metus aliquam ultricies iaculis, felis urna convallis nulla, vel faucibus leo erat et sem. Praesent volutpat at eros non sodales. Nunc sed posuere orci. Morbi finibus ac arcu sit amet posuere. Duis varius non enim eget molestie. Donec eu eros egestas, fringilla tortor in, feugiat lectus. Donec iaculis scelerisque sapien, et imperdiet nisl mollis vel.

Pellentesque et sollicitudin leo. Nullam eu rutrum nisl, vel viverra elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec nec mauris cursus, sagittis velit in, sollicitudin sapien. Pellentesque consectetur sem non vestibulum tincidunt. Mauris consequat suscipit auctor. Etiam non dui sagittis, porttitor nibh ac, fermentum ipsum. Etiam malesuada nisi sed felis accumsan pulvinar.

Nulla suscipit sapien sodales lorem interdum, at pellentesque nibh molestie. Etiam interdum auctor arcu id consectetur. Sed dapibus suscipit purus at auctor. Maecenas imperdiet venenatis volutpat. Praesent tellus dolor, posuere quis ipsum et, egestas maximus mauris. Ut eget massa non leo faucibus scelerisque ac in risus. In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer malesuada egestas massa, non scelerisque ligula scelerisque quis. Nullam venenatis massa ut lacus efficitur ullamcorper.

Donec sed leo semper, convallis neque sit amet, tempor lacus. Suspendisse at nunc a tellus pharetra aliquam eleifend sed ante. Quisque dictum consectetur lobortis. Donec mollis, massa sit amet ultricies pellentesque, tellus ipsum iaculis lectus, a lacinia sem est ut lorem. Curabitur ut magna eu nunc sagittis ullamcorper. Morbi non arcu maximus, varius magna non, venenatis sem. Etiam sed enim quis quam mollis viverra. Proin cursus elementum rhoncus. Ut sit amet varius tortor. Sed vel magna nec ipsum dictum finibus. Duis ultrices, erat sit amet ultrices semper, massa eros mattis risus, sed malesuada est tortor commodo massa. Maecenas vel ultricies mi, a fringilla arcu. Quisque interdum est vel ligula ornare, non venenatis orci tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ante elit, sagittis eget gravida eu, hendrerit et lectus.

Aenean at libero ut arcu tincidunt sagittis. Integer vel mi elit. Nulla facilisi. Proin sagittis nibh enim. Mauris ac feugiat sem. Quisque ultrices ante nec libero vehicula, ac scelerisque est vehicula. Cras faucibus vehicula tincidunt. Curabitur nibh diam, pellentesque ut varius et, congue a neque. Sed lacinia, metus ornare pulvinar placerat, neque magna pulvinar leo, vel imperdiet diam quam a velit.

Etiam tempor dignissim libero dignissim mattis. In nibh dolor, gravida nec tellus ut, tincidunt tristique tortor. Vivamus egestas, elit eget porttitor ultricies, dui elit iaculis tortor, sed ultricies purus orci vel tortor. Aenean auctor at arcu vitae congue. Nullam non leo eu nibh dapibus consequat. Vestibulum sollicitudin mi metus, eget rutrum dolor ultricies a. In mollis libero eu tortor vehicula eleifend.

Nullam a libero a quam porttitor ornare vel sed diam. Cras lacinia lobortis arcu, eget pharetra nunc gravida eu. Nulla egestas, dui ac dignissim pulvinar, nibh lectus ultricies justo, et auctor ex lorem bibendum tortor. Donec aliquam urna in sollicitudin pretium. Pellentesque efficitur nunc at ante viverra, sed facilisis ex vehicula. Maecenas interdum eleifend nibh, vitae lacinia sem dapibus quis. Sed efficitur eros a iaculis fermentum. Integer sodales, nulla eget efficitur laoreet, erat libero placerat dui, lacinia gravida lorem nulla sed massa. Ut ligula purus, convallis et dui tristique, ultricies accumsan mi. Aliquam elementum efficitur nisi, id tempor nunc malesuada in. Mauris nulla libero, vestibulum sit amet justo id, faucibus vestibulum mi. Pellentesque commodo dignissim pellentesque. Nam tincidunt ante ante, ut volutpat elit dictum at. Etiam aliquet pharetra sapien ac eleifend.

Pellentesque vitae blandit felis. Nulla vehicula ante eget quam lobortis tempor. Suspendisse potenti. Pellentesque aliquam erat at mattis dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam consequat aliquet quam, et maximus enim condimentum id. Vestibulum auctor lacinia commodo. Vestibulum eu condimentum erat, id commodo nisl. Sed mollis auctor metus, quis volutpat odio vulputate at. Nam magna massa, vulputate nec felis in, auctor efficitur ligula. Vestibulum sed augue tincidunt, aliquet nisl vel, facilisis diam.

Fusce sed est a velit dapibus consectetur et in nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam fringilla accumsan lorem, a molestie sapien efficitur in. Praesent lacinia, ipsum et blandit fringilla, neque lectus placerat sem, non suscipit leo nibh faucibus neque. In ac faucibus nisi. Donec eleifend consequat felis, at dignissim dolor venenatis sed. Vivamus scelerisque ante nisi, sit amet interdum magna vulputate nec. Sed ac magna nec eros ornare pharetra. Aenean fermentum elementum cursus. Suspendisse nec sagittis ipsum. Vivamus eu porttitor dui. Integer varius condimentum quam eget porta. Duis iaculis, enim sit amet fringilla sodales, libero dui ultricies mauris, et commodo eros lacus quis eros. Proin consequat dolor et augue bibendum, vel elementum arcu posuere. Vestibulum accumsan odio malesuada velit accumsan porta at in urna. Aenean sollicitudin arcu ut metus lobortis, ac fringilla ante finibus.
                </div>
            </div>
        )
    }
}

export default SuperTable;